#!/bin/sh
set -eu

if [ "${1:-}" = "--usage" ]; then
  printf '%s\n' \
    "--agreetolicense, agree to the license." \
    "--eraseinstall, erase the target volume." \
    "--installpackage, install a package <path>." \
    "--volume, target volume <path>."
  exit 0
fi
printf '%s\n' "$*" >> "$STARTOSINSTALL_LOG"
