#!/bin/sh
set -eu

output=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      output=$2
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

test -n "$output"
printf '%s\n' "prefetched artifact" > "$output"
